# pytagore:
#     # resource:
#     #     path: ../src/Controller/
#     #     namespace: App\Controller
#     # type: attribute

#     resource:
#         path: ../src/Controller/
#         controller: App\Controller\PythagoreController::displayPythagoreAction
#     # type: attribute


pythagore:
    path: /pythagore
    controller: App\Controller\PythagoreController::displayPythagoreAction
